name: Build Yu-OS ISO
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile Custom Arch Linux ISO
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm archiso squashfs-tools xorriso
          
          # Setup baseline mirror directory structures
          mkdir -p pacman.d
          echo "Server = https://pkgbuild.com\$repo/os/\$arch" > pacman.d/mirrorlist
          
          # Compile the system directly inside the root workspace folder
          chmod +x ./profiledef.sh
          mkarchiso -v -w /tmp/archiso-work -o ./out .

      - name: Upload Bootable ISO
        uses: actions/upload-artifact@v4
        with:
          name: Yu-OS-Bootable-ISO
          path: out/*.iso
